[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

[context.production.environment]
  NETLIFY = "true"

# 自定義部署命令
[context.production]
  command = "npm run build && npx wrangler deploy worker.js"

# 路由配置
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 