name = "fundingrate-web"
main = "worker.js"
compatibility_date = "2025-04-22"
workers_dev = true

[build]
command = "npm run build"

[site]
bucket = "./.next"

[env.production]
workers_dev = false
routes = ["fundingrate.peterlin.xyz/*"]

[triggers]
crons = [] 